name: Docker Image CI

on:
  push:
    branches:
    - main
    - master


jobs:
  build-and-push-image:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          ref: ${{ github.sha }}

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      # 修改登录步骤以使用私有registry的凭据
      - name: Login to Private Registry
        uses: docker/login-action@v2
        with:
          registry: dp-ve-registry-cn-beijing.cr.volces.com
          username: ${{ secrets.DOCKER_USERNAME_DP }}
          password: ${{ secrets.DOCKER_PASSWORD_DP }}

      # 添加步骤来获取当前日期并格式化为年月日形式
      - name: Get current date
        id: date
        run: |
          DATE=$(date +'%Y%m%d')
          echo "DATE=$DATE" >> $GITHUB_ENV

      # 添加步骤来根据分支名动态设置镜像名称前缀
      - name: Set image prefix based on branch
        id: image_prefix
        run: |
          if [[ $GITHUB_REF == refs/heads/main ]]; then
            echo "IMAGE_PREFIX=main" >> $GITHUB_ENV
          else
            echo "::error::Unsupported branch, no image will be built for this branch."
            exit 1
          fi

      # 添加步骤来获取当前的短SHA
      - name: Get short SHA
        id: sha
        run: echo "SHORT_SHA=${GITHUB_SHA::8}" >> $GITHUB_ENV

      # 修改构建和推送步骤，使用私有registry地址和指定的镜像名及标签
      - name: Build and push Docker image
        uses: docker/build-push-action@v3
        with:
          context: .
          file: github.Dockerfile
          push: true
          #  使用动态生成的日期作为标签的一部分，同时指定了私有registry的路径
          tags: |
            dp-ve-registry-cn-beijing.cr.volces.com/dplc/mol_infer_mcp_server:${{ env.IMAGE_PREFIX }}-${{ env.DATE }}-${{ env.SHORT_SHA }}
            dp-ve-registry-cn-beijing.cr.volces.com/dplc/mol_infer_mcp_server:latest
